/* a
SELECT MIN(low) AS Min_Temp
FROM FORECAST
WHERE CITY = 'Duluth'; */

/* b they both display the same thing. im not sure which is correct
fist method */
/*
SELECT DISTINCT CONSUMERS.PID, CONSUMERS.NAME
FROM CONSUMERS
JOIN ADDRESS ON CONSUMERS.PID = ADDRESS.PID
JOIN FORECAST ON ADDRESS.CITY = FORECAST.CITY; 
/* b 2nd method */
/*
SELECT DISTINCT CONSUMERS.PID, CONSUMERS.NAME, ADDRESS.PID, ADDRESS.CITY, FORECAST.CITY
FROM CONSUMERS, ADDRESS, FORECAST
WHERE CONSUMERS.PID = ADDRESS.PID AND ADDRESS.CITY = FORECAST.CITY; */








